
# MASTER:
# mysql -u root -p
# password

# ANY: MASTER/SLAVE
# To add rights to the user to create database (if needed).
# GRANT ALL PRIVILEGES ON *.* TO 'user'@'localhost' WITH GRANT OPTION;
# FLUSH PRIVILEGES;

# MASTER:
# CREATE USER 'slave_user'@'%' IDENTIFIED BY 'password';
# GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%';
# FLUSH PRIVILEGES;

# MASTER:
# CREATE DATABASE magento;
# USE magento;
# FLUSH TABLES WITH READ LOCK;

# MASTER:
# SHOW MASTER STATUS;
# Value from `File` column should be used for SOURCE_LOG_FILE value below.
# Value from `Position` column should be used for SOURCE_LOG_POS value below.
#
# Create db dump for future upload to the slave
# UNLOCK TABLES;

# SLAVE:
# SHOW REPLICA STATUS;
# RESET REPLICA;

# SLAVE:
# CHANGE REPLICATION SOURCE TO 
# SOURCE_HOST='mysqlmaster', 
# SOURCE_PORT = 3306, 
# SOURCE_USER='slave_user', 
# SOURCE_PASSWORD='password',
# SOURCE_LOG_FILE = 'binlog.000007', 
# SOURCE_LOG_POS = 446,
# GET_SOURCE_PUBLIC_KEY=1
# SHOW WARNINGS LIMIT 999;

# SLAVE:
# START REPLICA;

# MASTER:
# mysql --host=127.0.0.1 --port=3306 -u slave_user -p
# password

# SLAVE:
# mysql --host=mysqlmaster --port=3306 -u slave_user -p
# password

# TROUBLESHOUTING:

# SLAVE:
# SHOW REPLICA STATUS;
# Source_Log_File: mysql-bin.000001
# Read_Source_Log_Pos: 157

# SLAVE:
# RESET REPLICA

# SLAVE:
# CHANGE REPLICATION SOURCE TO 
# SOURCE_HOST='mysqlmaster', 
# SOURCE_PORT = 3306, 
# SOURCE_USER='slave_user', 
# SOURCE_PASSWORD='password',
# SOURCE_LOG_FILE = 'mysql-bin.000001', 
# SOURCE_LOG_POS = 157,
# GET_SOURCE_PUBLIC_KEY=1;
# SHOW WARNINGS LIMIT 999;

# SLAVE:
# START REPLICA;

version: "3"
services:
  mysql-master-db:
#    image: mysql:8.1.0
    build: .
    container_name: "mysql_db_master"
    user: "root:root"
    hostname: mysqlmaster
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db-volume:/var/lib/mysql
      - ../images/mysql/8.1.0/master/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mynetwork
      
  mysql-slave-db:
#    image: mysql:8.1.0
    build: .
    container_name: "mysql_db_slave"
    user: "root:root"
    hostname: mysqlslave
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql-slave-db-volume:/var/lib/mysql
      - ../images/mysql/8.1.0/slave/my.cnf:/etc/mysql/conf.d/my.cnf:rw
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-db-volume:
  mysql-slave-db-volume:
